const UNIVERSITIES = "universities";
const USERS = "users";
const DEPARTMENTS = "departments";
const COURSES = "courses";

export const endpoints = {
  LOGIN: USERS + "/login",
  REGISTER: USERS,
  GET_USER: USERS,
  FORGOT_PASSWORD: USERS,
  VERIFY_USER: USERS,
  GET_USERS: USERS,
  DELETE_USER: USERS,
  GET_UNIVERSITIES: UNIVERSITIES,
  GET_UNIVERSITY: UNIVERSITIES,
  CREATE_UNIVERSITY: UNIVERSITIES,
  UPDATE_UNIVERSITY: UNIVERSITIES,
  DELETE_UNIVERSITY: UNIVERSITIES,
  GET_DEPARTMENTS: DEPARTMENTS,
  CREATE_DEPARTMENT: DEPARTMENTS,
  GET_DEPARTMENT: DEPARTMENTS,
  UPDATE_DEPARTMENT: DEPARTMENTS,
  DELETE_DEPARTMENT: DEPARTMENTS,
  GET_COURSES: COURSES,
  GET_COURSE: COURSES,
  UPDATE_COURSE: COURSES,
  DELETE_COURSE: COURSES,
  CREATE_COURSE: COURSES,
};
